/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.54
 * Generated at: 2026-05-08 17:36:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.order;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/partials/footer.jsp", Long.valueOf(1778241570831L));
    _jspx_dependants.put("/views/partials/header.jsp", Long.valueOf(1778253436140L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // =========================================
    // GET CART FROM SESSION
    // =========================================

    java.util.Map<Integer, Integer> cart =
        (java.util.Map<Integer, Integer>)
        session.getAttribute("cart");

    int cartCount = 0;

    if (cart != null) {

        for (int qty : cart.values()) {

            cartCount += qty;
        }
    }

    // =========================================
    // USER SESSION
    // =========================================

    Object loggedUser =
            session.getAttribute("user");

    String userName =
            (String) session.getAttribute("userName");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"viewport\"\r\n");
      out.write("          content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <title>\r\n");
      out.write("\r\n");
      out.write("        CloudCart | Premium Ecommerce\r\n");
      out.write("\r\n");
      out.write("    </title>\r\n");
      out.write("\r\n");
      out.write("    <!-- GOOGLE FONT -->\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"preconnect\"\r\n");
      out.write("          href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"preconnect\"\r\n");
      out.write("          href=\"https://fonts.gstatic.com\"\r\n");
      out.write("          crossorigin>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&display=swap\"\r\n");
      out.write("          rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS -->\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("          href=\"");
      out.print( request.getContextPath() );
      out.write("/assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("          href=\"");
      out.print( request.getContextPath() );
      out.write("/assets/css/modern-ui.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- GSAP -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- HEADER STYLES -->\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        .cart-link {\r\n");
      out.write("\r\n");
      out.write("            position: relative;\r\n");
      out.write("\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart-badge {\r\n");
      out.write("\r\n");
      out.write("            position: absolute;\r\n");
      out.write("\r\n");
      out.write("            top: -6px;\r\n");
      out.write("            right: -10px;\r\n");
      out.write("\r\n");
      out.write("            background: #ef4444;\r\n");
      out.write("\r\n");
      out.write("            color: white;\r\n");
      out.write("\r\n");
      out.write("            font-size: 10px;\r\n");
      out.write("\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("\r\n");
      out.write("            padding: 2px 6px;\r\n");
      out.write("\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("\r\n");
      out.write("            min-width: 16px;\r\n");
      out.write("\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* AUTH BUTTONS */\r\n");
      out.write("\r\n");
      out.write("        .login-btn,\r\n");
      out.write("        .register-btn {\r\n");
      out.write("\r\n");
      out.write("            padding: 10px 18px;\r\n");
      out.write("\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("\r\n");
      out.write("            transition: 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-btn {\r\n");
      out.write("\r\n");
      out.write("            background:\r\n");
      out.write("                linear-gradient(\r\n");
      out.write("                    135deg,\r\n");
      out.write("                    #2563eb,\r\n");
      out.write("                    #1d4ed8\r\n");
      out.write("                );\r\n");
      out.write("\r\n");
      out.write("            color: #ffffff !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-btn:hover {\r\n");
      out.write("\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("\r\n");
      out.write("            box-shadow:\r\n");
      out.write("                0 10px 20px rgba(37,99,235,0.35);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-btn {\r\n");
      out.write("\r\n");
      out.write("            background:\r\n");
      out.write("                linear-gradient(\r\n");
      out.write("                    135deg,\r\n");
      out.write("                    #7c3aed,\r\n");
      out.write("                    #9333ea\r\n");
      out.write("                );\r\n");
      out.write("\r\n");
      out.write("            color: #ffffff !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-btn:hover {\r\n");
      out.write("\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("\r\n");
      out.write("            box-shadow:\r\n");
      out.write("                0 10px 20px rgba(124,58,237,0.35);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* USER */\r\n");
      out.write("\r\n");
      out.write("        .user-pill {\r\n");
      out.write("\r\n");
      out.write("            padding: 10px 16px;\r\n");
      out.write("\r\n");
      out.write("            border-radius: 14px;\r\n");
      out.write("\r\n");
      out.write("            background:\r\n");
      out.write("                rgba(255,255,255,0.08);\r\n");
      out.write("\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header class=\"header\">\r\n");
      out.write("\r\n");
      out.write("    <!-- LOGO -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("\r\n");
      out.write("        CLOUD<span>CART</span>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- SEARCH -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"search-bar\">\r\n");
      out.write("\r\n");
      out.write("        <form action=\"");
      out.print( request.getContextPath() );
      out.write("/product\"\r\n");
      out.write("              method=\"GET\">\r\n");
      out.write("\r\n");
      out.write("            <input type=\"text\"\r\n");
      out.write("                   name=\"search\"\r\n");
      out.write("\r\n");
      out.write("                   placeholder=\"Discover premium products...\">\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\">\r\n");
      out.write("\r\n");
      out.write("                🔍\r\n");
      out.write("\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- NAVIGATION -->\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"nav-links\">\r\n");
      out.write("\r\n");
      out.write("        <!-- HOME -->\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/user/home.jsp\">\r\n");
      out.write("\r\n");
      out.write("            Home\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <!-- PRODUCTS -->\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/product\">\r\n");
      out.write("\r\n");
      out.write("            Products\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <!-- CART -->\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/cart\"\r\n");
      out.write("           class=\"cart-link\">\r\n");
      out.write("\r\n");
      out.write("            🛒 Cart\r\n");
      out.write("\r\n");
      out.write("            ");
 if(cartCount > 0){ 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <span class=\"cart-badge\">\r\n");
      out.write("\r\n");
      out.write("                    ");
      out.print( cartCount );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </span>\r\n");
      out.write("\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <!-- AUTH -->\r\n");
      out.write("\r\n");
      out.write("        ");
 if(loggedUser == null){ 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- LOGIN -->\r\n");
      out.write("\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/auth?action=login\"\r\n");
      out.write("               class=\"login-btn\">\r\n");
      out.write("\r\n");
      out.write("                Login\r\n");
      out.write("\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- REGISTER -->\r\n");
      out.write("\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/auth?action=register\"\r\n");
      out.write("               class=\"register-btn\">\r\n");
      out.write("\r\n");
      out.write("                Register\r\n");
      out.write("\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- USER -->\r\n");
      out.write("\r\n");
      out.write("       <!-- MINI USER ICON -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"user-menu\">\r\n");
      out.write("\r\n");
      out.write("    <!-- AVATAR -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"nav-avatar\">\r\n");
      out.write("\r\n");
      out.write("        ");
      out.print( userName.substring(0,1).toUpperCase() );
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- DROPDOWN -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"user-dropdown\">\r\n");
      out.write("\r\n");
      out.write("        <!-- USER INFO -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"dropdown-user\">\r\n");
      out.write("\r\n");
      out.write("            <h4>\r\n");
      out.write("\r\n");
      out.write("                ");
      out.print( userName );
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </h4>\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("\r\n");
      out.write("                Premium Account\r\n");
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- MENU OPTIONS -->\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/wishlist\">\r\n");
      out.write("\r\n");
      out.write("            ❤️ Wishlist\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/orders\">\r\n");
      out.write("\r\n");
      out.write("            📦 My Orders\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/order-history\">\r\n");
      out.write("\r\n");
      out.write("            🧾 Order History\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/cart\">\r\n");
      out.write("\r\n");
      out.write("            🛒 My Cart\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/profile\">\r\n");
      out.write("\r\n");
      out.write("            👤 User Profile\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/settings\">\r\n");
      out.write("\r\n");
      out.write("            ⚙️ Account Settings\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/wishlist-page\">\r\n");
      out.write("\r\n");
      out.write("            💖 Wishlist Page\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/logout\"\r\n");
      out.write("           class=\"logout-link\">\r\n");
      out.write("\r\n");
      out.write("            🚪 Logout\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("href=\"");
      out.print( request.getContextPath() );
      out.write("/assets/css/checkout.css\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"checkout-container\">\r\n");
      out.write("\r\n");
      out.write("    <h1 class=\"checkout-title\">\r\n");
      out.write("\r\n");
      out.write("        🛍️ Secure Checkout\r\n");
      out.write("\r\n");
      out.write("    </h1>\r\n");
      out.write("\r\n");
      out.write("    <!-- FORM START -->\r\n");
      out.write("\r\n");
      out.write("    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/place-order\"\r\n");
      out.write("          method=\"post\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"checkout-layout\">\r\n");
      out.write("\r\n");
      out.write("            <!-- LEFT -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"checkout-left\">\r\n");
      out.write("\r\n");
      out.write("                <!-- SHIPPING -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("                    <h2>\r\n");
      out.write("\r\n");
      out.write("                        Shipping Address\r\n");
      out.write("\r\n");
      out.write("                    </h2>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                        <label>\r\n");
      out.write("\r\n");
      out.write("                            Full Address\r\n");
      out.write("\r\n");
      out.write("                        </label>\r\n");
      out.write("\r\n");
      out.write("                        <textarea\r\n");
      out.write("                            name=\"address\"\r\n");
      out.write("                            required\r\n");
      out.write("                            placeholder=\"Enter your address\"></textarea>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                            <label>\r\n");
      out.write("\r\n");
      out.write("                                City\r\n");
      out.write("\r\n");
      out.write("                            </label>\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"text\"\r\n");
      out.write("                                   name=\"city\"\r\n");
      out.write("                                   required\r\n");
      out.write("                                   placeholder=\"City\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                            <label>\r\n");
      out.write("\r\n");
      out.write("                                State\r\n");
      out.write("\r\n");
      out.write("                            </label>\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"text\"\r\n");
      out.write("                                   name=\"state\"\r\n");
      out.write("                                   required\r\n");
      out.write("                                   placeholder=\"State\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                            <label>\r\n");
      out.write("\r\n");
      out.write("                                Pincode\r\n");
      out.write("\r\n");
      out.write("                            </label>\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"text\"\r\n");
      out.write("                                   name=\"pincode\"\r\n");
      out.write("                                   required\r\n");
      out.write("                                   placeholder=\"Pincode\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                            <label>\r\n");
      out.write("\r\n");
      out.write("                                Phone\r\n");
      out.write("\r\n");
      out.write("                            </label>\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"text\"\r\n");
      out.write("                                   name=\"phone\"\r\n");
      out.write("                                   required\r\n");
      out.write("                                   placeholder=\"Phone\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- PAYMENT -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("                    <h2>\r\n");
      out.write("\r\n");
      out.write("                        Payment Method\r\n");
      out.write("\r\n");
      out.write("                    </h2>\r\n");
      out.write("\r\n");
      out.write("                    <!-- COD -->\r\n");
      out.write("\r\n");
      out.write("                    <label class=\"payment-option\">\r\n");
      out.write("\r\n");
      out.write("                        <input type=\"radio\"\r\n");
      out.write("                               name=\"payment\"\r\n");
      out.write("                               value=\"COD\"\r\n");
      out.write("                               checked>\r\n");
      out.write("\r\n");
      out.write("                        Cash On Delivery\r\n");
      out.write("\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <!-- UPI -->\r\n");
      out.write("\r\n");
      out.write("                    <label class=\"payment-option\">\r\n");
      out.write("\r\n");
      out.write("                        <input type=\"radio\"\r\n");
      out.write("                               name=\"payment\"\r\n");
      out.write("                               value=\"UPI\">\r\n");
      out.write("\r\n");
      out.write("                        UPI Payment\r\n");
      out.write("                        (GPay / PhonePe / Paytm)\r\n");
      out.write("\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <!-- CARD -->\r\n");
      out.write("\r\n");
      out.write("                    <label class=\"payment-option\">\r\n");
      out.write("\r\n");
      out.write("                        <input type=\"radio\"\r\n");
      out.write("                               name=\"payment\"\r\n");
      out.write("                               value=\"CARD\">\r\n");
      out.write("\r\n");
      out.write("                        Credit / Debit Card\r\n");
      out.write("\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <!-- CARD SECTION -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"card-payment-box\">\r\n");
      out.write("\r\n");
      out.write("                        <h3>\r\n");
      out.write("\r\n");
      out.write("                            💳 Card Details\r\n");
      out.write("\r\n");
      out.write("                        </h3>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"text\"\r\n");
      out.write("                                   placeholder=\"Card Holder Name\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"text\"\r\n");
      out.write("                                   placeholder=\"Card Number\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                                <input type=\"text\"\r\n");
      out.write("                                       placeholder=\"MM/YY\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                                <input type=\"password\"\r\n");
      out.write("                                       placeholder=\"CVV\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- OFFERS -->\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"offer-box\">\r\n");
      out.write("\r\n");
      out.write("                            <h4>\r\n");
      out.write("\r\n");
      out.write("                                🎉 Bank Offers\r\n");
      out.write("\r\n");
      out.write("                            </h4>\r\n");
      out.write("\r\n");
      out.write("                            <p>\r\n");
      out.write("\r\n");
      out.write("                                • 10% OFF on HDFC Cards\r\n");
      out.write("\r\n");
      out.write("                            </p>\r\n");
      out.write("\r\n");
      out.write("                            <p>\r\n");
      out.write("\r\n");
      out.write("                                • Flat ₹500 OFF on ICICI Credit Cards\r\n");
      out.write("\r\n");
      out.write("                            </p>\r\n");
      out.write("\r\n");
      out.write("                            <p>\r\n");
      out.write("\r\n");
      out.write("                                • 5% Cashback on SBI Debit Cards\r\n");
      out.write("\r\n");
      out.write("                            </p>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- UPI SECTION -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"upi-box\">\r\n");
      out.write("\r\n");
      out.write("                        <h3>\r\n");
      out.write("\r\n");
      out.write("                            📱 Choose UPI App\r\n");
      out.write("\r\n");
      out.write("                        </h3>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"upi-apps\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"upi-app\">\r\n");
      out.write("\r\n");
      out.write("                                🟣 PhonePe\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"upi-app\">\r\n");
      out.write("\r\n");
      out.write("                                🟢 Google Pay\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"upi-app\">\r\n");
      out.write("\r\n");
      out.write("                                🔵 Paytm\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- RIGHT -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"checkout-right\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("                    <h2>\r\n");
      out.write("\r\n");
      out.write("                        Order Summary\r\n");
      out.write("\r\n");
      out.write("                    </h2>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"summary-item\">\r\n");
      out.write("\r\n");
      out.write("                        <span>\r\n");
      out.write("\r\n");
      out.write("                            Subtotal\r\n");
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                        <span>\r\n");
      out.write("\r\n");
      out.write("                            ₹");
      out.print( request.getAttribute("total") );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"summary-item\">\r\n");
      out.write("\r\n");
      out.write("                        <span>\r\n");
      out.write("\r\n");
      out.write("                            Delivery\r\n");
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                        <span>\r\n");
      out.write("\r\n");
      out.write("                            FREE\r\n");
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"summary-total\">\r\n");
      out.write("\r\n");
      out.write("                        <span>\r\n");
      out.write("\r\n");
      out.write("                            Total\r\n");
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                        <span>\r\n");
      out.write("\r\n");
      out.write("                            ₹");
      out.print( request.getAttribute("total") );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- BUTTON -->\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\"\r\n");
      out.write("                            class=\"place-order-btn\">\r\n");
      out.write("\r\n");
      out.write("                        Place Order\r\n");
      out.write("\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("const paymentRadios =\r\n");
      out.write("document.querySelectorAll(\r\n");
      out.write("'input[name=\"payment\"]'\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("const upiBox =\r\n");
      out.write("document.querySelector('.upi-box');\r\n");
      out.write("\r\n");
      out.write("const cardBox =\r\n");
      out.write("document.querySelector('.card-payment-box');\r\n");
      out.write("\r\n");
      out.write("function updatePaymentUI(){\r\n");
      out.write("\r\n");
      out.write("    let selected =\r\n");
      out.write("    document.querySelector(\r\n");
      out.write("    'input[name=\"payment\"]:checked'\r\n");
      out.write("    ).value;\r\n");
      out.write("\r\n");
      out.write("    upiBox.style.display =\r\n");
      out.write("    selected === 'UPI'\r\n");
      out.write("    ? 'block'\r\n");
      out.write("    : 'none';\r\n");
      out.write("\r\n");
      out.write("    cardBox.style.display =\r\n");
      out.write("    selected === 'CARD'\r\n");
      out.write("    ? 'block'\r\n");
      out.write("    : 'none';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("paymentRadios.forEach(radio => {\r\n");
      out.write("\r\n");
      out.write("    radio.addEventListener(\r\n");
      out.write("    'change',\r\n");
      out.write("    updatePaymentUI\r\n");
      out.write("    );\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("updatePaymentUI();\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"footer\">\n");
      out.write("    <div class=\"footer-content\">\n");
      out.write("        <p>&copy; 2026 CloudCart | Designed for Premium Excellence</p>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<!-- Modern UI Logic -->\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/assets/js/modern-ui.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
